use_frameworks!

target 'TwitterProfile_Example' do
  pod 'TwitterProfile', :path => '../'
  pod 'XLPagerTabStrip', '~> 9.0'

  target 'TwitterProfile_Tests' do
    inherit! :search_paths

    
  end
end
